<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class VehicleCertificate extends Model
{
    protected $table = 'vehicle_certificates';

    protected $fillable = [

        'company_id',
        'supervisor_id',

        'certificate_type',
        'vehicle_registration_no',

        'vehicle_make',
        'vehicle_model',
        'chassis_no',
        'engine_no',
        'vehicle_emission_norm',
        'date_of_registration',

        'tank_type',
        'cce_no',
        'calibration',
        'capacity',
        'no_of_compartments',
        'compartment_details',

        'transporter_name',
        'transporter_contact',
        'contact_person',
        'driver_name',
        'driver_mobile',

        'vin_no',

        'suraksha_centre_location',
        'inspector_name',
        'inspection_supervisor',
        'inspection_supervisor_contact',
        'principal_client_contact',

        'last_product_carried',

        'certificate_no',
        'certificate_date',
        'certificate_valid_to',
        'date_of_first_inspection',
        'last_suraksha_details',

        'inspection_result',

        'remark',
        'vehicle_photo',

        'status',
        'is_read',
        'is_deleted',

        /* CHECKLIST */

        'explosive_license',
        'rc_book',
        'insurance',
        'tank_truck_fitness',
        'puc_certificate',
        'road_tax',
        'permit',
        'driving_licence_details',
        'hazardous_endorsement',
        'fire_extinguisher_certificate',
        'last_suraksha_certificate',
        'tank_calibration_certificate',
        'speed_governor_certificate',
        'chassis_number_impression',
        'safety_triangle',
        'class_label',
        'wiper_system',
        'windscreen_glass',
        'front_lights_indicator',
        'retro_reflective_white',
        'front_bumper',
        'registration_plate',
        'radiator_condition',
        'unauthorized_modification_top',
        'tank_width_height',
        'spark_arrestor',
        'rhs_door_handle',
        'rhs_mirror',
        'fuel_tank',
        'rhs_cabin_mounting',
        'distance_cabin_tank',
        'rhs_cabin_exterior',
        'engine_noise',
        'retro_reflective_yellow',
        'lupd_1',
        'registration_rhs',
        'eip_panel',
        'rhs_tyre',
        'retro_reflective_red',
        'rupd',
        'registration_rear',
        'rear_lights',
        'unauthorized_chassis_modification',
        'reverse_buzzer',
        'rear_bumper',
        'registration_lhs',
        'eip_lhs',
        'lupd_2',
        'retro_reflective_yellow_lhs',
        'lhs_tyre',
        'spare_wheel',
        'lhs_cabin_mounting',
        'lhs_door_handle',
        'lhs_mirror',
        'spray_suppression_flap',
        'fire_extinguisher_10kg',
        'seat_belts',
        'hand_brake',
        'first_aid_kit',
        'safety_kit',
        'fire_extinguisher_cabin',
        'electrical_wiring',
        'battery',
        'battery_cutoff_switch',
        'horn',
        'cabin_interior',
        'rear_window',
        'co_driver_seat',
        'starter',
        'sleeping_berth',
        'steering',
        'vts_fitment',
        'tool_kit',
        'abs_functioning',
        'drag_link',
        'fuel_lines',
        'oil_leakage_notice',
        'long_member_condition',
        'riveting_condition',
        'cj_rubber',
        'uj_cross',
        'yoke_condition',
        'exhaust_system',
        'brake_chamber',
        'fifth_wheel',
        'engine_mounting',
        'tank_mounting_clamp',
        'bonding_strip',
        'landing_gear',
        'external_leakage',
        'compartment_valves',
        'inter_compartment_test',
        'catwalk_path',
        'caps_on_faucets',
        'master_valve',
        'toe_guard',
        'dip_pipe',
        'dome_cover',
        'fill_pipe',
        'earthing_lug',
        'coaming_arrangement',
        'tanker_colour',
        'ril_colour_code',
        'pressure_vacuum_valve',
        'slope_channel',
        'faucet_valve_box',
        'fusible_link',
        'intermediate_flanges',
        'spindle_holes',
        'master_valve_box',
        'erc_tollfree_paint',
    ];

}